CREATE DATABASE IF NOT EXISTS OCTIMINE;

USE OCTIMINE;

CREATE TABLE IF NOT EXISTS `banking_records` (
  `id` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(128) DEFAULT NULL,
  `age` int(3) unsigned DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;